#!/usr/bin/with-contenv bash
# shellcheck shell=bash

cd /app/www/server || exit 1

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 3000" \
    s6-setuidgid abc /usr/bin/node index.js
